### ISSUE TITLE
Question | How will it still load?

### ISSUE THREAD

**Issue by MirayXS** [SiLeNSwOrD/OwlHub#1]
# How will it still load?

You stated in the readme.md that it will stop loading if the owlhub’s repository gets shut down. If it does, how will it still load? I could re-host it on GitHub..

**Comment by SiLeNSwOrD** [comment]
It can Be loaded via this loadstring

`loadstring(game:HttpGet("https://raw.githubusercontent.com/ZinityDrops/OwlHubLink/master/OwlHubBack.lua"))();`

As I have stated That the Loader is offline now and to check out a v3million post
