### ISSUE TITLE
Script Not Working

### ISSUE THREAD

**Issue by CostilierLynx** [SiLeNSwOrD/OwlHub#4]
This script have stopped working since day before yesterday.

Executor used- Synapse X and Pardella

**Comment by MirayXS** [comment]
tf is Pardella
never heard of it lol
looks like a shit name

**Comment by egssy0** [comment]
this script not workin for kids

**Comment by SiLeNSwOrD** [comment]
Works fine for me 

Maybe dont use some pasted shit called Pardella

Case Closed
